const formInputs = [
  {
    labelDataTestid: 'title-input-label',
    labelHtmlFor: 'title-input',
    labelValue: 'Título',
    inputName: 'titleInput',
    dataTestid: 'title-input',
    type: 'text',
    value: { title },
  },
  {
    labelDataTestid: 'subtitle-input-label',
    labelHtmlFor: 'subtitleInput',
    labelValue: 'Subtítulo',
    inputName: 'subtitleInput',
    dataTestid: 'subtitle-input',
    type: 'text',
    value: { title },
  },
  {
    labelDataTestid: 'image-input-label',
    labelHtmlFor: 'image-input',
    labelValue: 'Caminho da imagem',
    inputName: 'image-input',
    dataTestid: 'image-input',
    type: 'text',
    value: { imagePath },
  },
  {
    labelDataTestid: 'storyline-input-label',
    labelHtmlFor: 'storyline-input',
    labelValue: 'Sinopse',
    inputName: 'storyline-input',
    dataTestid: 'storyline-input',
    type: 'text',
    value: { storyline },
  },
];
